# Generated by Django 3.2.7 on 2022-07-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_timage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timage',
            old_name='timg',
            new_name='photo',
        ),
    ]
