# Generated by Django 3.2.7 on 2022-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220723_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passion', models.CharField(max_length=300)),
                ('twitter', models.TextField()),
                ('facebook', models.TextField()),
                ('insta', models.TextField()),
                ('linked', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation', models.TextField()),
                ('p_image', models.ImageField(upload_to='myimage')),
                ('twitter', models.TextField()),
                ('facebook', models.TextField()),
                ('insta', models.TextField()),
                ('linked', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passion', models.CharField(max_length=200)),
                ('graduation', models.TextField()),
                ('testimonial_image', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Teacher',
        ),
    ]
