# Generated by Django 3.2.7 on 2022-07-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220725_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.DeleteModel(
            name='Student10',
        ),
        migrations.DeleteModel(
            name='Student12',
        ),
    ]
