# Generated by Django 3.2.7 on 2022-07-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220725_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='passout',
            name='passout_imgage',
            field=models.ImageField(default='Image', upload_to='myimage'),
        ),
    ]
