# Generated by Django 3.2.7 on 2022-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_passout_passout_imgage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
            ],
        ),
    ]
