# Generated by Django 3.2.7 on 2022-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_student10'),
    ]

    operations = [
        migrations.AddField(
            model_name='student10',
            name='s_image',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
