# Generated by Django 3.2.7 on 2022-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_student10_s_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
                ('s_image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='passout',
            name='passout_imgage',
            field=models.ImageField(upload_to='image'),
        ),
    ]
