# Generated by Django 3.2.7 on 2022-07-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20220726_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student10',
            old_name='s10_image',
            new_name='s_image',
        ),
    ]
